# Generated by Django 5.2.1 on 2025-05-27 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Semester 1', 'BHCS-Y-1-S-1'), ('Semester 2', 'BHCS-Y-1-S-2'), ('Semester 3', 'BHCS-Y-2-S-3'), ('Semester 4', 'BHCS-Y-2-S-4'), ('Semester 5', 'BHCS-Y-3-S-5'), ('Semester 6', 'BHCS-Y-3-S-6')], default='Semester 1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('Year 1', 'BHCS-Y-1'), ('Year 2', 'BHCS-Y-2'), ('Year 3', 'BHCS-Y-3')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, choices=[('semester 1 | Year 1', [('Programming Fundamental & C', 'Programming Fundamental & C'), ('Introduction to Web and HTML', 'Introduction to Web and HTML'), ('Digital Electronics', 'Digital Electronics'), ('Maths I', 'Maths I'), ('Environmental Studies', 'Environmental Studies'), ('C/ C++ Programming Lab', 'C/ C++ Programming Lab'), ('Web Programming Lab', 'Web Programming Lab')]), ('semester 2 | Year 1', [('Data Structure', 'Data Structure'), ('Maths II', 'Maths II'), ('Professional Communication', 'Professional Communication'), ('Computer Organization and Architecture', 'Computer Organization and Architecture'), ('Human Values and Professional Ethics', 'Human Values and Professional Ethics'), ('Data Structure Lab', 'Data Structure Lab'), ('CBNST LAB', 'CBNST LAB')]), ('semester 3 | Year 2', [('Statistical Computing With R Programming', 'Statistical Computing With R Programming'), ('DBMS and SQL/ PLSQL', 'DBMS and SQL/ PLSQL'), ('Mathematics III', 'Mathematics III'), ('Operating System', 'Operating System'), ('R Programming Lab', 'R Programming Lab'), ('DBMS LAB', 'DBMS LAB')]), ('semester 4 | Year 2', [('Java Programming', 'Java Programming'), ('Computer Networks', 'Computer Networks'), ('Design and Analysis of Algorithms', 'Design and Analysis of Algorithms'), ('Compiler Design', 'Compiler Design'), ('Java Programming Lab', 'Java Programming Lab'), ('Design and Analysis of Algorithms Lab', 'Design and Analysis of Algorithms Lab')]), ('semester 5 | Year 3', [('Interactive Computer Graphics & Multimedia', 'Interactive Computer Graphics & Multimedia'), ('Software Engineering', 'Software Engineering'), ('Introduction to Artificial Intelligence', 'Introduction to Artificial Intelligence'), ('Analytical Programming Using Python Concepts', 'Analytical Programming Using Python Concepts'), ('Computer Graphics Lab', 'Computer Graphics Lab')]), ('semester 6 | Year 3', [('IoT & Cloud Computing', 'IoT & Cloud Computing'), ('Information Security & Cyber Laws', 'Information Security & Cyber Laws'), ('Soft Computing', 'Soft Computing'), ('Data Science and Machine Learning Techniques', 'Data Science and Machine Learning Techniques')])], max_length=100, null=True)),
                ('resource_type', models.CharField(choices=[('PYQs', 'Previous Year Question Paper'), ('BOOK', 'BOOK'), ('Youtube Video URL', 'Youtube Video URL'), ('Syllabus', 'Syllabus')], max_length=20)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='PDF/')),
                ('resource_file_year', models.IntegerField(blank=True, choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], null=True)),
                ('resource_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('url_source', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.semester')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.year'),
        ),
    ]
