# Generated by Django 5.1.7 on 2025-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="is_ignored",
            field=models.BooleanField(default=False),
        ),
    ]
